# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteedu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Post',
        ),
    ]
